/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bethorse.ig_bethorse;

import java.awt.*;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author 22159675
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(50, 50, 50));
        URL url = this.getClass().getResource("/Imagens/cavalo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadCorrida = new javax.swing.JButton();
        btnAposta = new javax.swing.JButton();
        btnDono = new javax.swing.JButton();
        btnRunCorrida = new javax.swing.JButton();
        conteudo = new javax.swing.JPanel();
        CadRace = new javax.swing.JPanel();
        addLocal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeRace = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDistancia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        selectLocal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        selectTipo = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        aposta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        selectAp = new javax.swing.JComboBox<>();
        selectRace = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAp = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        seeAp = new javax.swing.JButton();
        seeRace = new javax.swing.JButton();
        dono = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        btnCav = new javax.swing.JButton();
        btnJoq = new javax.swing.JButton();
        btnCor = new javax.swing.JButton();
        txtCpf = new javax.swing.JTextField();
        runCorrida = new javax.swing.JPanel();
        fzrCorrida = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultCorrida = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        selRace = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCadCorrida.setBackground(new java.awt.Color(66, 66, 66));
        btnCadCorrida.setForeground(new java.awt.Color(255, 255, 255));
        btnCadCorrida.setText("Cadastrar Corridas");
        btnCadCorrida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadCorridaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadCorridaMouseExited(evt);
            }
        });
        btnCadCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCorridaActionPerformed(evt);
            }
        });

        btnAposta.setBackground(new java.awt.Color(66, 66, 66));
        btnAposta.setForeground(new java.awt.Color(255, 255, 255));
        btnAposta.setText("Aposta");
        btnAposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApostaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApostaMouseExited(evt);
            }
        });
        btnAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostaActionPerformed(evt);
            }
        });

        btnDono.setBackground(new java.awt.Color(66, 66, 66));
        btnDono.setForeground(new java.awt.Color(255, 255, 255));
        btnDono.setText("Dono");
        btnDono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDonoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDonoMouseExited(evt);
            }
        });
        btnDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonoActionPerformed(evt);
            }
        });

        btnRunCorrida.setBackground(new java.awt.Color(66, 66, 66));
        btnRunCorrida.setForeground(new java.awt.Color(255, 255, 255));
        btnRunCorrida.setText("Corrida");
        btnRunCorrida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRunCorridaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRunCorridaMouseExited(evt);
            }
        });
        btnRunCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunCorridaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
            .addComponent(btnDono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRunCorrida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnCadCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnDono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnRunCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conteudo.setLayout(new java.awt.CardLayout());

        CadRace.setBackground(new java.awt.Color(50, 50, 50));
        CadRace.setForeground(new java.awt.Color(255, 255, 255));

        addLocal.setBackground(new java.awt.Color(0, 74, 173));
        addLocal.setForeground(new java.awt.Color(255, 255, 255));
        addLocal.setText("Adicionar Local ");
        addLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome Corrida");

        txtNomeRace.setBackground(new java.awt.Color(128, 128, 128));
        txtNomeRace.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRaceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Distancia");

        txtDistancia.setBackground(new java.awt.Color(128, 128, 128));
        txtDistancia.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Local");

        selectLocal.setBackground(new java.awt.Color(128, 128, 128));
        selectLocal.setForeground(new java.awt.Color(255, 255, 255));
        selectLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Onde será a Corrida?" }));
        selectLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLocalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Corrida");

        selectTipo.setBackground(new java.awt.Color(128, 128, 128));
        selectTipo.setForeground(new java.awt.Color(255, 255, 255));
        selectTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classificação da Corrida" }));
        selectTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(0, 74, 173));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Corrida");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adicionar Local");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome Lugar");

        txtLocal.setBackground(new java.awt.Color(128, 128, 128));
        txtLocal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CadRaceLayout = new javax.swing.GroupLayout(CadRace);
        CadRace.setLayout(CadRaceLayout);
        CadRaceLayout.setHorizontalGroup(
            CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadRaceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433))
            .addGroup(CadRaceLayout.createSequentialGroup()
                .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadRaceLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDistancia)
                                .addComponent(txtNomeRace)
                                .addComponent(selectLocal, 0, 500, Short.MAX_VALUE)
                                .addComponent(selectTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)))
                    .addGroup(CadRaceLayout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel5))
                    .addGroup(CadRaceLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(addLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        CadRaceLayout.setVerticalGroup(
            CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadRaceLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selectLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(selectTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(addLocal)
                .addGap(28, 28, 28))
        );

        conteudo.add(CadRace, "CadRace");

        aposta.setBackground(new java.awt.Color(50, 50, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dados das corridas");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apostador");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Corrida");

        selectAp.setBackground(new java.awt.Color(128, 128, 128));
        selectAp.setForeground(new java.awt.Color(255, 255, 255));

        selectRace.setBackground(new java.awt.Color(128, 128, 128));
        selectRace.setForeground(new java.awt.Color(255, 255, 255));
        selectRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRaceActionPerformed(evt);
            }
        });

        listaAp.setBackground(new java.awt.Color(128, 128, 128));
        listaAp.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listaAp);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SELECT DA CORRIDA COM OS DADOS DE CIMA");

        jButton2.setBackground(new java.awt.Color(0, 74, 173));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Excluir aposta");

        jLabel16.setBackground(new java.awt.Color(128, 128, 128));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(128, 128, 128));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));

        seeAp.setText("ok");
        seeAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeApActionPerformed(evt);
            }
        });

        seeRace.setText("ok");
        seeRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeRaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apostaLayout = new javax.swing.GroupLayout(aposta);
        aposta.setLayout(apostaLayout);
        apostaLayout.setHorizontalGroup(
            apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostaLayout.createSequentialGroup()
                .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apostaLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel8))
                    .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, apostaLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(apostaLayout.createSequentialGroup()
                                    .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selectRace, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectAp, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(seeAp, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(seeRace, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(apostaLayout.createSequentialGroup()
                                    .addGap(186, 186, 186)
                                    .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, apostaLayout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apostaLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apostaLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apostaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(288, 288, 288))))
        );
        apostaLayout.setVerticalGroup(
            apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(seeAp))
                .addGap(54, 54, 54)
                .addGroup(apostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(seeRace))
                .addGap(73, 73, 73)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(68, 68, 68)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(42, 42, 42))
        );

        conteudo.add(aposta, "aposta");

        dono.setBackground(new java.awt.Color(50, 50, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Dados do Dono");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CPF Dono");

        jButton6.setBackground(new java.awt.Color(0, 74, 173));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Excluir conta");

        lista.setBackground(new java.awt.Color(128, 128, 128));
        lista.setForeground(new java.awt.Color(255, 255, 255));
        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Selecione os dados..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lista);

        btnCav.setBackground(new java.awt.Color(0, 74, 173));
        btnCav.setForeground(new java.awt.Color(255, 255, 255));
        btnCav.setText("Cavalos");
        btnCav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCavActionPerformed(evt);
            }
        });

        btnJoq.setBackground(new java.awt.Color(0, 74, 173));
        btnJoq.setForeground(new java.awt.Color(255, 255, 255));
        btnJoq.setText("Joqueis");
        btnJoq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoqActionPerformed(evt);
            }
        });

        btnCor.setBackground(new java.awt.Color(0, 74, 173));
        btnCor.setForeground(new java.awt.Color(255, 255, 255));
        btnCor.setText("Corridas");
        btnCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorActionPerformed(evt);
            }
        });

        txtCpf.setText("Insira o CPF");
        txtCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCpfMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout donoLayout = new javax.swing.GroupLayout(dono);
        dono.setLayout(donoLayout);
        donoLayout.setHorizontalGroup(
            donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donoLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(donoLayout.createSequentialGroup()
                        .addComponent(btnCav, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(btnJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 268, Short.MAX_VALUE))
            .addGroup(donoLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donoLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donoLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donoLayout.createSequentialGroup()
                        .addGroup(donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCpf)
                            .addComponent(jLabel10))
                        .addGap(276, 276, 276))))
        );
        donoLayout.setVerticalGroup(
            donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(donoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton6)
                .addGap(42, 42, 42))
        );

        conteudo.add(dono, "dono");

        runCorrida.setBackground(new java.awt.Color(50, 50, 50));

        fzrCorrida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a corrida..." }));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Corrida");

        resultCorrida.setBackground(new java.awt.Color(128, 128, 128));
        resultCorrida.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(resultCorrida);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Selecione a Corrida");

        selRace.setText("Selecionar");
        selRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selRaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout runCorridaLayout = new javax.swing.GroupLayout(runCorrida);
        runCorrida.setLayout(runCorridaLayout);
        runCorridaLayout.setHorizontalGroup(
            runCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runCorridaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(runCorridaLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(fzrCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selRace, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, runCorridaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(runCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(410, 410, 410))
        );
        runCorridaLayout.setVerticalGroup(
            runCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runCorridaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(runCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fzrCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selRace))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        conteudo.add(runCorrida, "runCorrida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCorridaActionPerformed
        CardLayout c1 = (CardLayout) conteudo.getLayout();
        c1.show(conteudo,"CadRace");
        mostrarClasse();
        mostrarLocal();
    }//GEN-LAST:event_btnCadCorridaActionPerformed

    private void btnDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonoActionPerformed
        CardLayout c1 = (CardLayout) conteudo.getLayout();
        c1.show(conteudo,"dono");
    }//GEN-LAST:event_btnDonoActionPerformed

    private void btnApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostaActionPerformed
        CardLayout c1 = (CardLayout) conteudo.getLayout();
        c1.show(conteudo,"aposta");
        
        selectAp();
        selectCor();
    }//GEN-LAST:event_btnApostaActionPerformed

    private void selectRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectRaceActionPerformed

    private void txtNomeRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRaceActionPerformed

    private void btnCadCorridaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadCorridaMouseEntered
        btnCadCorrida.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_btnCadCorridaMouseEntered

    private void btnCadCorridaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadCorridaMouseExited
        btnCadCorrida.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_btnCadCorridaMouseExited

    private void btnDonoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonoMouseEntered
        btnDono.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_btnDonoMouseEntered

    private void btnDonoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonoMouseExited
        btnDono.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_btnDonoMouseExited

    private void btnApostaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApostaMouseEntered
        btnAposta.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_btnApostaMouseEntered

    private void btnApostaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApostaMouseExited
        btnAposta.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_btnApostaMouseExited

    private void addLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocalActionPerformed
        String nomeLocal = txtLocal.getText();
        try{
            String query = "INSERT INTO lugar VALUES(null, ?)";
            PreparedStatement stat = con.prepareStatement(query);
            stat.setString(1, nomeLocal);
            stat.execute();
            JOptionPane.showMessageDialog(null, "Local incluso com sucesso", "Local", JOptionPane.INFORMATION_MESSAGE);
            txtLocal.setText("");
            selectLocal.addItem(nomeLocal);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro!!\n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addLocalActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nomeCorrida = txtNomeRace.getText();
        Float distancia = Float.parseFloat(txtDistancia.getText());
        int local = selectLocal.getSelectedIndex();
        int tipo = selectTipo.getSelectedIndex();
        try{
            String query = "INSERT INTO corrida VALUES(null, ?, ?, ?, ?, ?, ?);";
            PreparedStatement stat = con.prepareStatement(query);
            stat.setString(1, nomeCorrida);
            stat.setString(2, distancia+"km");
            stat.setFloat(3, 0);
            stat.setInt(4, local);
            stat.setInt(5, tipo);
            stat.setString(6, "Aberta");
            stat.execute();
            JOptionPane.showMessageDialog(null, "Corrida adicionada com sucesso", "Corrida", JOptionPane.INFORMATION_MESSAGE);
            txtNomeRace.setText("");
            txtDistancia.setText("");
            selectLocal.setSelectedIndex(0);
            selectTipo.setSelectedIndex(0);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro!!\n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCavActionPerformed
        long cpf = Long.parseLong(txtCpf.getText());
        BuscarInfo info = new BuscarInfo();
        lista.setModel(info.pegarCavalos(cpf));
    }//GEN-LAST:event_btnCavActionPerformed

    private void btnJoqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoqActionPerformed
        long cpf = Long.parseLong(txtCpf.getText());
        BuscarInfo info = new BuscarInfo();
        lista.setModel(info.buscarJoqueis(cpf));
    }//GEN-LAST:event_btnJoqActionPerformed

    public DefaultListModel mostrarCorridasDono(long cpf){
        
        ConexaoBD cbd = new ConexaoBD();
        Connection con = cbd.connectionMySql();
        
        DefaultListModel model = new DefaultListModel();
        
        try{
            String sqlIdCav = "SELECT idCavalo, nomeCavalo FROM cavalo WHERE cpfDono = ?;";
            PreparedStatement st = con.prepareStatement(sqlIdCav);
            st.setLong(1, cpf);
            ResultSet rs = st.executeQuery();
            
            while (rs.next()){
                int idCav = rs.getInt("idCavalo");
                String nomeCav = rs.getString("nomeCavalo");
                
                String sqlIdCor = "SELECT idCorrida FROM cavalo_corrida WHERE idCavalo = ?;";
                st = con.prepareStatement(sqlIdCor);
                st.setInt(1, idCav);
                ResultSet res = st.executeQuery();
                
                while (res.next()){
                    int idCor = res.getInt("idCorrida");
                    
                    String sqlNomeCor = "SELECT nomeCorrida FROM corrida WHERE idCorrida = ?;";
                    st = con.prepareStatement(sqlNomeCor);
                    st.setInt(1, idCor);
                    ResultSet result = st.executeQuery();
                    
                    while (result.next()){
                        String nomeCor = result.getString("nomeCorrida");
                        
                        String devolve = nomeCor + " --> " +nomeCav;
                        model.addElement(devolve);
                    }
                }
                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro!\n" + e, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        cbd.closeConnectionMySql(con);
        return model;
    }
    
    public void mostrarLocal(){
        
        ConexaoBD cbd = new ConexaoBD();
        Connection con = cbd.connectionMySql();
        
        selectLocal.removeAllItems();
        selectLocal.addItem("Onde será a corrida?");
        
        try{
            String sql = "SELECT * FROM lugar;";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()){
                selectLocal.addItem(rs.getString("nomeLocal"));
            }
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro!\n" + e, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        cbd.closeConnectionMySql(con);
    }
    
    public void mostrarClasse(){
        ConexaoBD cbd = new ConexaoBD();
        Connection con = cbd.connectionMySql();
        
        selectLocal.removeAllItems();
        selectLocal.addItem("Classificação da corrida");
        
        String classe = "";
        try{
            String select = "SELECT * FROM TIPO_CORRIDA";
            PreparedStatement pstm = con.prepareStatement(select);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
                classe = rs.getString("tipoCorrida");
                selectTipo.addItem(classe);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro!\n" + e, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        cbd.closeConnectionMySql(con);
    }
    
    public void selectAp(){
        ConexaoBD cbd = new ConexaoBD();
        Connection con = cbd.connectionMySql();
        
        selectAp.removeAllItems();
        selectAp.addItem("Selecione o usuário...");
        
        try{
            String sql = "SELECT nome FROM usuario;";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()){
                selectAp.addItem(rs.getString("nome"));
            }
        } catch(Exception e){
            System.out.println(e);
        }
        cbd.closeConnectionMySql(con);
    }

    public void selectCor(){
        
        BuscarInfo info = new BuscarInfo();
        DefaultListModel model = info.buscarCorridas("");
        
        selectRace.removeAllItems();
        selectRace.addItem("Selecione a corrida...");
        
        for (int i = 0; i < model.size(); i++){
            selectRace.addItem(String.valueOf(model.getElementAt(i)));
        }
    }
    
    private void btnCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorActionPerformed
        long cpf = Long.parseLong(txtCpf.getText());
        lista.setModel(mostrarCorridasDono(cpf));
    }//GEN-LAST:event_btnCorActionPerformed

    private void txtCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCpfMouseClicked
        if(txtCpf.getText().equals("Insira o CPF")){
            txtCpf.setText("");
        }else if(txtCpf.getText().equals("")){
            txtCpf.setText("Insira o CPF");
        }
    }//GEN-LAST:event_txtCpfMouseClicked

    private void selectLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectLocalActionPerformed

    private void selectTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoActionPerformed

    private void seeApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeApActionPerformed
        // TODO add your handling code here:
        BuscarInfo info = new BuscarInfo();
        
        String nome = selectAp.getSelectedItem().toString();
        listaAp.setModel(info.getApostas(nome));
    }//GEN-LAST:event_seeApActionPerformed

    private void seeRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeRaceActionPerformed
        // TODO add your handling code here:
        BuscarInfo info = new BuscarInfo();
        
        String nome = selectRace.getSelectedItem().toString();
        listaAp.setModel(info.getApostasCorridas(nome));
    }//GEN-LAST:event_seeRaceActionPerformed

    private void btnRunCorridaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRunCorridaMouseEntered
        // TODO add your handling code here:
        btnRunCorrida.setBackground(new Color(0, 74, 173));
    }//GEN-LAST:event_btnRunCorridaMouseEntered

    private void btnRunCorridaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRunCorridaMouseExited
         // TODO add your handling code here:
         btnRunCorrida.setBackground(new Color(66,66,66));
    }//GEN-LAST:event_btnRunCorridaMouseExited

    private void btnRunCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunCorridaActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) conteudo.getLayout();
        c1.show(conteudo,"runCorrida");
        
        BuscarInfo info = new BuscarInfo();
        DefaultListModel model = info.buscarCorridas("Fechada");
        
        fzrCorrida.removeAllItems();
        fzrCorrida.addItem("Selecione a corrida...");
        
        for (int i = 0; i < model.size(); i++){
            fzrCorrida.addItem(String.valueOf(model.getElementAt(i)));
        }
    }//GEN-LAST:event_btnRunCorridaActionPerformed

    private void selRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selRaceActionPerformed
        // TODO add your handling code here:
        String corrida = fzrCorrida.getSelectedItem().toString();
        String[] corName = corrida.split(" -->");
        
        RealizaCorrida rc = new RealizaCorrida();
        rc.ranking(corName[0]);
        resultCorrida.setModel(rc.getModel());
        selectCor();
    }//GEN-LAST:event_selRaceActionPerformed

    ConexaoBD cbd = new ConexaoBD();
    Connection con = cbd.connectionMySql();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadRace;
    private javax.swing.JButton addLocal;
    private javax.swing.JPanel aposta;
    private javax.swing.JButton btnAposta;
    private javax.swing.JButton btnCadCorrida;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCav;
    private javax.swing.JButton btnCor;
    private javax.swing.JButton btnDono;
    private javax.swing.JButton btnJoq;
    private javax.swing.JButton btnRunCorrida;
    private javax.swing.JPanel conteudo;
    private javax.swing.JPanel dono;
    private javax.swing.JComboBox<String> fzrCorrida;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista;
    private javax.swing.JList<String> listaAp;
    private javax.swing.JList<String> resultCorrida;
    private javax.swing.JPanel runCorrida;
    private javax.swing.JButton seeAp;
    private javax.swing.JButton seeRace;
    private javax.swing.JToggleButton selRace;
    private javax.swing.JComboBox<String> selectAp;
    private javax.swing.JComboBox<String> selectLocal;
    private javax.swing.JComboBox<String> selectRace;
    private javax.swing.JComboBox<String> selectTipo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNomeRace;
    // End of variables declaration//GEN-END:variables
}
