/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bethorse.ig_bethorse;

import java.awt.*;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Lins
 */
public class usuApostador extends javax.swing.JFrame {

    /**
     * Creates new form usuApostador
     */
    public usuApostador() {
        initComponents();
        //setExtendedState(usuApostador.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(50, 50, 50));
        URL url = this.getClass().getResource("/Imagens/cavalo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        apHistBut = new javax.swing.JButton();
        apostarBut = new javax.swing.JButton();
        apHomeBut = new javax.swing.JButton();
        apPerfilBut = new javax.swing.JButton();
        cardsAp = new javax.swing.JPanel();
        homeAp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        adiciSaldobut = new javax.swing.JButton();
        adiciSaldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apostar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        selectCavalo = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        selectCorrida = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        historicoAp = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hist = new javax.swing.JList<>();
        perfilAp = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mudarSenhaBut = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        MudSenha = new javax.swing.JPasswordField();
        mudarSenha = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nomeUser = new javax.swing.JLabel();
        senhaUser = new javax.swing.JLabel();
        telUser = new javax.swing.JLabel();
        cpfUser = new javax.swing.JLabel();
        emailUser = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        exibirSenha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(50, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 574));

        apHistBut.setBackground(new java.awt.Color(66, 66, 66));
        apHistBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apHistBut.setForeground(new java.awt.Color(255, 255, 255));
        apHistBut.setText("Histórico");
        apHistBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apHistButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apHistButMouseExited(evt);
            }
        });
        apHistBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apHistButActionPerformed(evt);
            }
        });

        apostarBut.setBackground(new java.awt.Color(66, 66, 66));
        apostarBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apostarBut.setForeground(new java.awt.Color(255, 255, 255));
        apostarBut.setText("Apostar");
        apostarBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apostarButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apostarButMouseExited(evt);
            }
        });
        apostarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarButActionPerformed(evt);
            }
        });

        apHomeBut.setBackground(new java.awt.Color(66, 66, 66));
        apHomeBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apHomeBut.setForeground(new java.awt.Color(255, 255, 255));
        apHomeBut.setText("Home");
        apHomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apHomeButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apHomeButMouseExited(evt);
            }
        });
        apHomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apHomeButActionPerformed(evt);
            }
        });

        apPerfilBut.setBackground(new java.awt.Color(66, 66, 66));
        apPerfilBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apPerfilBut.setForeground(new java.awt.Color(255, 255, 255));
        apPerfilBut.setText("Perfil");
        apPerfilBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                apPerfilButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                apPerfilButMouseExited(evt);
            }
        });
        apPerfilBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apPerfilButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apostarBut, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addComponent(apHistBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(apHomeBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(apPerfilBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(apHomeBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(apostarBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(apHistBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(apPerfilBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardsAp.setLayout(new java.awt.CardLayout());

        homeAp.setBackground(new java.awt.Color(50, 50, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bem Vindo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Olá!");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Últimas apostas");

        jList1.setBackground(new java.awt.Color(128, 128, 128));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Adicionar Saldo");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Saldo Atual");

        adiciSaldobut.setBackground(new java.awt.Color(0, 74, 173));
        adiciSaldobut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adiciSaldobut.setForeground(new java.awt.Color(255, 255, 255));
        adiciSaldobut.setText("Adicionar");
        adiciSaldobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiciSaldobutActionPerformed(evt);
            }
        });

        adiciSaldo.setBackground(new java.awt.Color(128, 128, 128));
        adiciSaldo.setForeground(new java.awt.Color(255, 255, 255));
        adiciSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiciSaldoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(128, 128, 128));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout homeApLayout = new javax.swing.GroupLayout(homeAp);
        homeAp.setLayout(homeApLayout);
        homeApLayout.setHorizontalGroup(
            homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeApLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(289, 289, 289))
            .addGroup(homeApLayout.createSequentialGroup()
                .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeApLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(adiciSaldobut))
                    .addGroup(homeApLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeApLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeApLayout.createSequentialGroup()
                        .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adiciSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeApLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(321, 321, 321))))
        );
        homeApLayout.setVerticalGroup(
            homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeApLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(homeApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adiciSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(adiciSaldobut)
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardsAp.add(homeAp, "homeAp");

        apostar.setBackground(new java.awt.Color(50, 50, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bem Vindo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Olá!");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Corredores");

        selectCavalo.setBackground(new java.awt.Color(128, 128, 128));
        selectCavalo.setForeground(new java.awt.Color(255, 255, 255));
        selectCavalo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o cavalo ..." }));
        selectCavalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCavaloActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Valor da aposta");

        selectCorrida.setBackground(new java.awt.Color(128, 128, 128));
        selectCorrida.setForeground(new java.awt.Color(255, 255, 255));
        selectCorrida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Corrida ..." }));
        selectCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCorridaActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Corridas");

        jButton4.setBackground(new java.awt.Color(0, 74, 173));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Entrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total a Ganhar: ");

        jLabel20.setBackground(new java.awt.Color(128, 128, 128));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("R$");

        txtvalor.setBackground(new java.awt.Color(128, 128, 128));
        txtvalor.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apostarLayout = new javax.swing.GroupLayout(apostar);
        apostar.setLayout(apostarLayout);
        apostarLayout.setHorizontalGroup(
            apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostarLayout.createSequentialGroup()
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apostarLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(apostarLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(apostarLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel27))
                .addGap(9, 9, 9)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apostarLayout.createSequentialGroup()
                        .addComponent(selectCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(selectCavalo, 0, 440, Short.MAX_VALUE)
                        .addComponent(txtvalor)))
                .addGap(0, 87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apostarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        apostarLayout.setVerticalGroup(
            apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(selectCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(selectCavalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(apostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        cardsAp.add(apostar, "apostar");

        historicoAp.setBackground(new java.awt.Color(50, 50, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bem Vindo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Olá!");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Histórico estendido");

        hist.setBackground(new java.awt.Color(128, 128, 128));
        hist.setForeground(new java.awt.Color(255, 255, 255));
        hist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(hist);

        javax.swing.GroupLayout historicoApLayout = new javax.swing.GroupLayout(historicoAp);
        historicoAp.setLayout(historicoApLayout);
        historicoApLayout.setHorizontalGroup(
            historicoApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historicoApLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoApLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(296, 296, 296))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historicoApLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(289, 289, 289))
        );
        historicoApLayout.setVerticalGroup(
            historicoApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historicoApLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(historicoApLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardsAp.add(historicoAp, "historicoAp");

        perfilAp.setBackground(new java.awt.Color(50, 50, 50));
        perfilAp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bem Vindo");
        perfilAp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 41, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Olá!");
        perfilAp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 41, -1, -1));

        mudarSenhaBut.setBackground(new java.awt.Color(0, 74, 173));
        mudarSenhaBut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mudarSenhaBut.setForeground(new java.awt.Color(255, 255, 255));
        mudarSenhaBut.setText("Trocar Senha");
        mudarSenhaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarSenhaButActionPerformed(evt);
            }
        });
        perfilAp.add(mudarSenhaBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 444, 202, 75));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Email");
        perfilAp.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 220, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Senha");
        perfilAp.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 349, -1, -1));

        MudSenha.setBackground(new java.awt.Color(128, 128, 128));
        perfilAp.add(MudSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 392, 577, 30));

        mudarSenha.setBackground(new java.awt.Color(128, 128, 128));
        mudarSenha.setForeground(new java.awt.Color(255, 255, 255));
        mudarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarSenhaActionPerformed(evt);
            }
        });
        perfilAp.add(mudarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 392, 578, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nome");
        perfilAp.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 163, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Telefone");
        perfilAp.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 258, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Trocar Senha");
        perfilAp.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 392, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CPF");
        perfilAp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 306, -1, -1));

        nomeUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeUser.setForeground(new java.awt.Color(255, 255, 255));
        perfilAp.add(nomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 163, 578, 32));

        senhaUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        senhaUser.setForeground(new java.awt.Color(255, 255, 255));
        perfilAp.add(senhaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 349, 578, 32));

        telUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telUser.setForeground(new java.awt.Color(255, 255, 255));
        perfilAp.add(telUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 258, 578, 32));

        cpfUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cpfUser.setForeground(new java.awt.Color(255, 255, 255));
        perfilAp.add(cpfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 299, 578, 32));

        emailUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailUser.setForeground(new java.awt.Color(255, 255, 255));
        perfilAp.add(emailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 213, 578, 32));

        back.setText("Sair");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        perfilAp.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 603, -1, -1));

        exibirSenha.setText("Mostrar Senha");
        exibirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirSenhaActionPerformed(evt);
            }
        });
        perfilAp.add(exibirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        cardsAp.add(perfilAp, "perfilAp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardsAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apHomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apHomeButActionPerformed
        CardLayout c1 = (CardLayout) cardsAp.getLayout();
        c1.show(cardsAp,"homeAp");
    }//GEN-LAST:event_apHomeButActionPerformed

    private void apHistButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apHistButActionPerformed
        CardLayout c1 = (CardLayout) cardsAp.getLayout();
        c1.show(cardsAp,"historicoAp");
        
        BuscarInfo info = new BuscarInfo();
        
        DefaultListModel model = info.getApostas(nomeAp());
        hist.setModel(model);
    }//GEN-LAST:event_apHistButActionPerformed

    private void apostarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostarButActionPerformed
        CardLayout c1 = (CardLayout) cardsAp.getLayout();
        c1.show(cardsAp,"apostar");
        selectCor();
    }//GEN-LAST:event_apostarButActionPerformed

    public void selectCor(){
        BuscarInfo info = new BuscarInfo();
        DefaultListModel dlm = info.buscarCorridas("Fechada");
        
        selectCorrida.removeAllItems();
        selectCorrida.addItem("Selecione a corrida...");
        
        for (int i = 0; i < dlm.size(); i++){
            selectCorrida.addItem(String.valueOf(dlm.getElementAt(i)));
        }
    }
    
    public void selectCav(){
        Dono dn = new Dono();
        
        String corrida = selectCorrida.getSelectedItem().toString();
        String [] corName = corrida.split(" -->");
        
        String race = corName[0];
        
        DefaultListModel dlm = dn.cavalosCorrida(race);
        
        selectCavalo.removeAllItems();
        selectCavalo.addItem("Selecione o cavalo...");
        
        for (int i = 0; i < dlm.size(); i++){
            selectCavalo.addItem(String.valueOf(dlm.getElementAt(i)));
        }
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Aposta ap = new Aposta();
        usuDono dn = new usuDono();
        
        String cavalo = selectCavalo.getSelectedItem().toString();
        String nome = dn.repararString(cavalo)[0];
        String dados = ap.getDados(nome);
        
        float odd = ap.calcularOdds(dados);
        JOptionPane.showMessageDialog(null, "Valor da Odd: " + df.format(odd));
        float valor = Float.parseFloat(txtvalor.getText());
        
        int op = JOptionPane.showConfirmDialog(null, "Você poderá ganhar " +df.format(valor*odd) + " com sua aposta de " + df.format(valor) + ".\nDeseja apostar?", "Aposta", JOptionPane.YES_NO_OPTION);
        if (op == 0){
            AddCred cr = new AddCred();
            if (cr.pegarSaldo(con, email) >= valor){
                cr.Remover(con, email, valor);
                String corrida = selectCorrida.getSelectedItem().toString();
                ap.criarAposta(pegarCpf(), valor, corrida, nome);
                jLabel2.setText(String.valueOf(df.format(cr.pegarSaldo(con, email))));
            } else {
                JOptionPane.showMessageDialog(null, "Saldo insuficiente! Adicione saldo na página inicial", "Sem créditos", JOptionPane.ERROR_MESSAGE);
            }
            jLabel20.setText(df.format(valor*odd));
        }
        selectCor();
        selectCav();
        txtvalor.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mudarSenhaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarSenhaButActionPerformed
        // TODO add your handling code here:
        Dono dn = new Dono();
        String oldSenha = senhaUser.getText();
        String novaSenha = MudSenha.getText();
        
        String senha = JOptionPane.showInputDialog("Qual a sua senha atual?");
        if (senha.equals(oldSenha)){
            int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo mudar a sua senha?", "Mudar senha", JOptionPane.YES_NO_OPTION);
            if (op == 0){
                dn.trocarSenha(con, pegarCpf(), oldSenha, novaSenha);
                newSenha = dn.mostrarSenha(con, pegarCpf(), emailUser.getText());
                senhaUser.setText(newSenha);   
                MudSenha.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha errada!!", "Mudar senha", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mudarSenhaButActionPerformed

    private void adiciSaldobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiciSaldobutActionPerformed
        // TODO add your handling code here:
        AddCred adcr = new AddCred();
        
        float valor = Float.parseFloat(adiciSaldo.getText());
        int op = JOptionPane.showConfirmDialog(null, "Deseja adicionar " +df.format(valor) +" de créditos?", "Adição de créditos", JOptionPane.OK_CANCEL_OPTION);
        if (op == 0){
            adcr.Adicionar(con, email, valor);
            saldo = adcr.pegarSaldo(con, email);
            jLabel2.setText(String.valueOf(df.format(saldo)));
            JOptionPane.showMessageDialog(null, "Foram adicionados " +df.format(valor) +" de créditos na sua conta.\nSeu saldo agora é de " +df.format(saldo), "´Créditos adicionados", JOptionPane.INFORMATION_MESSAGE);
            adiciSaldo.setText("");
        }
    }//GEN-LAST:event_adiciSaldobutActionPerformed

    private void adiciSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiciSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adiciSaldoActionPerformed

    public long pegarCpf(){
        ConexaoBD cbd = new ConexaoBD();
        Connection con = cbd.connectionMySql();
        
        long cpf = 0;
        try{
            String query = "SELECT cpf FROM usuario WHERE email = ?;";
            PreparedStatement stat = con.prepareStatement(query);
            stat.setString(1, email);
            ResultSet result  = stat.executeQuery();
            while (result.next()){
                cpf = result.getLong("cpf");
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro!!\n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        return cpf;
    }
    
    public String nomeAp(){
        
        String nome = "";
        try{
            String sql = "SELECT nome FROM usuario WHERE cpf = " +pegarCpf();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()){
                nome = rs.getString("nome");
            }
        } catch (SQLException e){
            System.out.println(e);
        }
        return nome;
    }
    
    public ArrayList mostrarDadosAp(){
        ArrayList dados = new ArrayList();
        try{
            String sql = "SELECT * FROM usuario WHERE cpf = ?;";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setLong(1, pegarCpf());
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
                dados.add(rs.getLong("cpf"));
                dados.add(rs.getString("nome"));
                dados.add(rs.getString("senha"));
                dados.add(rs.getString("email"));
                dados.add(rs.getString("telefone"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
        return dados;
    }
    
    private void apPerfilButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apPerfilButActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) cardsAp.getLayout();
        c1.show(cardsAp,"perfilAp");        
        
        ArrayList dados = new ArrayList();
        for(Object d : mostrarDadosAp()){
            dados.add(d);
        }
        cpfUser.setText(dados.get(0).toString());
        nomeUser.setText(dados.get(1).toString());
        senhaUser.setText(dados.get(2).toString());
        emailUser.setText(dados.get(3).toString());
        telUser.setText(dados.get(4).toString());
    }//GEN-LAST:event_apPerfilButActionPerformed

    private void apHomeButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apHomeButMouseEntered
        apHomeBut.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_apHomeButMouseEntered

    private void apHomeButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apHomeButMouseExited
        apHomeBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_apHomeButMouseExited

    private void apostarButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apostarButMouseEntered
        apostarBut.setBackground(new Color(0, 74, 173)); // TODO add your handling code here:
    }//GEN-LAST:event_apostarButMouseEntered

    private void apostarButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apostarButMouseExited
        apostarBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_apostarButMouseExited

    private void apHistButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apHistButMouseEntered
        apHistBut.setBackground(new Color(0, 74, 173)); // TODO add your handling code here:
    }//GEN-LAST:event_apHistButMouseEntered

    private void apHistButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apHistButMouseExited
        apHistBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_apHistButMouseExited

    private void apPerfilButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apPerfilButMouseEntered
        apPerfilBut.setBackground(new Color(0, 74, 173)); // TODO add your handling code here:
    }//GEN-LAST:event_apPerfilButMouseEntered

    private void apPerfilButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apPerfilButMouseExited
        apPerfilBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_apPerfilButMouseExited

    private void selectCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCorridaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selectCav();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectCavaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCavaloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCavaloActionPerformed

    private void exibirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirSenhaActionPerformed
        // TODO add your handling code here:
        if(exibirSenha.isSelected()){
            MudSenha.setEchoChar('\u0000');
        }  
        else {
            MudSenha.setEchoChar('*'); 
        }
    }//GEN-LAST:event_exibirSenhaActionPerformed

    private void mudarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mudarSenhaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        
        if(op == 0){
            Login log = new Login();
            log.setVisible(true);
            log.setLocationRelativeTo(null);
            dispose();
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuApostador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuApostador().setVisible(true);
            }
        });
    }
    Connection con;
    String email;
    int tipo;
    String newSenha;
    float saldo;
    DecimalFormat df = new DecimalFormat("R$ #,##0.00");

    public void recebe(Connection conec, String em, float sal){
        con = conec;
        email = em;
        saldo = sal;
        
        String[] nome= nomeAp().split(" ");
        
        jLabel3.setText("Bem-vindo, " + nome[0]);
        jLabel5.setText("Bem-vindo, " + nome[0]);
        jLabel7.setText("Bem-vindo, " + nome[0]);
        jLabel9.setText("Bem-vindo, " + nome[0]);
        jLabel2.setText(String.valueOf(df.format(saldo)));
        BuscarInfo info = new BuscarInfo();
        jList1.setModel(info.getApostas(nomeAp()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField MudSenha;
    private javax.swing.JTextField adiciSaldo;
    private javax.swing.JButton adiciSaldobut;
    private javax.swing.JButton apHistBut;
    private javax.swing.JButton apHomeBut;
    private javax.swing.JButton apPerfilBut;
    private javax.swing.JPanel apostar;
    private javax.swing.JButton apostarBut;
    private javax.swing.JButton back;
    private javax.swing.JPanel cardsAp;
    private javax.swing.JLabel cpfUser;
    private javax.swing.JLabel emailUser;
    private javax.swing.JCheckBox exibirSenha;
    private javax.swing.JList<String> hist;
    private javax.swing.JPanel historicoAp;
    private javax.swing.JPanel homeAp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mudarSenha;
    private javax.swing.JButton mudarSenhaBut;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JPanel perfilAp;
    private javax.swing.JComboBox<String> selectCavalo;
    private javax.swing.JComboBox<String> selectCorrida;
    private javax.swing.JLabel senhaUser;
    private javax.swing.JLabel telUser;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
