/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bethorse.ig_bethorse;

import java.awt.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.font.FontManager;

/**
 *
 * @author Lins
 */
public class usuDono extends javax.swing.JFrame {

    /**
     * Creates new form usuDono
     */
    Font antonio = null;
    public usuDono() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(50, 50, 50));
        URL url = this.getClass().getResource("/Imagens/cavalo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perfClick = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homeBut = new javax.swing.JButton();
        cavCadBut = new javax.swing.JButton();
        cadJoqBut = new javax.swing.JButton();
        cadCavBut = new javax.swing.JButton();
        entCorriBut = new javax.swing.JButton();
        entPerfil = new javax.swing.JButton();
        cards = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adiciSaldo = new javax.swing.JTextField();
        adiciSaldobut = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        topCav = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cavalosCad = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCav = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cadJoquei = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        entrarInfoJoquei = new javax.swing.JButton();
        telJoq = new javax.swing.JTextField();
        alturaJoq = new javax.swing.JTextField();
        pesoJoq = new javax.swing.JTextField();
        idadeJoq = new javax.swing.JTextField();
        nomeJoq = new javax.swing.JTextField();
        emailJoq = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cpfJoq = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cadCavalo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idadeCav = new javax.swing.JTextField();
        pesoCav = new javax.swing.JTextField();
        nomeCav = new javax.swing.JTextField();
        entrarInfoCavalo = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        racaCav = new javax.swing.JComboBox<>();
        corrida = new javax.swing.JPanel();
        selectCorrida = new javax.swing.JComboBox<>();
        selectCav = new javax.swing.JComboBox<>();
        selectJoq = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnEntrarCorrida = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblgasto = new javax.swing.JLabel();
        perfil = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        mudarSenhaBut = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        telUser = new javax.swing.JLabel();
        nomeUser = new javax.swing.JLabel();
        cpfUser = new javax.swing.JLabel();
        emailUser = new javax.swing.JLabel();
        senhaUser = new javax.swing.JLabel();
        MudSenha = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        mostrarSenha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        perfClick.setFocusCycleRoot(true);
        perfClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perfClickMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        homeBut.setBackground(new java.awt.Color(66, 66, 66));
        homeBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeBut.setForeground(new java.awt.Color(255, 255, 255));
        homeBut.setText("Home");
        homeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButMouseExited(evt);
            }
        });
        homeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButActionPerformed(evt);
            }
        });

        cavCadBut.setBackground(new java.awt.Color(66, 66, 66));
        cavCadBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cavCadBut.setForeground(new java.awt.Color(255, 255, 255));
        cavCadBut.setText("Cavalos Cadastrados");
        cavCadBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cavCadButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cavCadButMouseExited(evt);
            }
        });
        cavCadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cavCadButActionPerformed(evt);
            }
        });

        cadJoqBut.setBackground(new java.awt.Color(66, 66, 66));
        cadJoqBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadJoqBut.setForeground(new java.awt.Color(255, 255, 255));
        cadJoqBut.setText("Cadastro do jóquei");
        cadJoqBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadJoqButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadJoqButMouseExited(evt);
            }
        });
        cadJoqBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadJoqButActionPerformed(evt);
            }
        });

        cadCavBut.setBackground(new java.awt.Color(66, 66, 66));
        cadCavBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadCavBut.setForeground(new java.awt.Color(255, 255, 255));
        cadCavBut.setText("Cadastro de Cavalos");
        cadCavBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadCavButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadCavButMouseExited(evt);
            }
        });
        cadCavBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCavButActionPerformed(evt);
            }
        });

        entCorriBut.setBackground(new java.awt.Color(66, 66, 66));
        entCorriBut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entCorriBut.setForeground(new java.awt.Color(255, 255, 255));
        entCorriBut.setText("Entrar em Corrida");
        entCorriBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entCorriButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entCorriButMouseExited(evt);
            }
        });
        entCorriBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entCorriButActionPerformed(evt);
            }
        });

        entPerfil.setBackground(new java.awt.Color(66, 66, 66));
        entPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        entPerfil.setForeground(new java.awt.Color(255, 255, 255));
        entPerfil.setText("Perfil");
        entPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entPerfilMouseExited(evt);
            }
        });
        entPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cavCadBut, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(cadCavBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cadJoqBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(entCorriBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(entPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(homeBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cavCadBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cadJoqBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(cadCavBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(entCorriBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(entPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cards.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(50, 50, 50));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+36f));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Olá!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bem Vindo");

        adiciSaldo.setBackground(new java.awt.Color(128, 128, 128));
        adiciSaldo.setForeground(new java.awt.Color(255, 255, 255));

        adiciSaldobut.setBackground(new java.awt.Color(0, 74, 173));
        adiciSaldobut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adiciSaldobut.setForeground(new java.awt.Color(255, 255, 255));
        adiciSaldobut.setText("Adicionar");
        adiciSaldobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiciSaldobutActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Saldo Atual");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Adicionar Saldo");

        topCav.setBackground(new java.awt.Color(128, 128, 128));
        topCav.setForeground(new java.awt.Color(255, 255, 255));
        topCav.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(topCav);

        jLabel22.setBackground(new java.awt.Color(128, 128, 128));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jLabel22InputMethodTextChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Top 3 Cavalos");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addGap(0, 156, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(362, 362, 362)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adiciSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(415, 415, 415))
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(adiciSaldobut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adiciSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addComponent(adiciSaldobut)
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        cards.add(home, "home");

        cavalosCad.setBackground(new java.awt.Color(50, 50, 50));

        listaCav.setBackground(new java.awt.Color(128, 128, 128));
        listaCav.setForeground(new java.awt.Color(255, 255, 255));
        listaCav.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaCav);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cavalos Cadastrados");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bem Vindo");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Olá!");

        javax.swing.GroupLayout cavalosCadLayout = new javax.swing.GroupLayout(cavalosCad);
        cavalosCad.setLayout(cavalosCadLayout);
        cavalosCadLayout.setHorizontalGroup(
            cavalosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cavalosCadLayout.createSequentialGroup()
                .addGap(0, 157, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cavalosCadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(363, 363, 363))
            .addGroup(cavalosCadLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cavalosCadLayout.setVerticalGroup(
            cavalosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cavalosCadLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(cavalosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cards.add(cavalosCad, "cavalosCad");

        cadJoquei.setBackground(new java.awt.Color(50, 50, 50));
        cadJoquei.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Idade");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peso");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Altura");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefone");

        entrarInfoJoquei.setBackground(new java.awt.Color(0, 74, 173));
        entrarInfoJoquei.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entrarInfoJoquei.setForeground(new java.awt.Color(255, 255, 255));
        entrarInfoJoquei.setText("Cadastrar");
        entrarInfoJoquei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarInfoJoqueiActionPerformed(evt);
            }
        });

        telJoq.setBackground(new java.awt.Color(128, 128, 128));
        telJoq.setForeground(new java.awt.Color(255, 255, 255));
        telJoq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telJoqActionPerformed(evt);
            }
        });

        alturaJoq.setBackground(new java.awt.Color(128, 128, 128));
        alturaJoq.setForeground(new java.awt.Color(255, 255, 255));

        pesoJoq.setBackground(new java.awt.Color(128, 128, 128));
        pesoJoq.setForeground(new java.awt.Color(255, 255, 255));

        idadeJoq.setBackground(new java.awt.Color(128, 128, 128));
        idadeJoq.setForeground(new java.awt.Color(255, 255, 255));

        nomeJoq.setBackground(new java.awt.Color(128, 128, 128));
        nomeJoq.setForeground(new java.awt.Color(255, 255, 255));

        emailJoq.setBackground(new java.awt.Color(128, 128, 128));
        emailJoq.setForeground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Olá!");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Bem Vindo");

        cpfJoq.setBackground(new java.awt.Color(128, 128, 128));
        cpfJoq.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CPF");

        javax.swing.GroupLayout cadJoqueiLayout = new javax.swing.GroupLayout(cadJoquei);
        cadJoquei.setLayout(cadJoqueiLayout);
        cadJoqueiLayout.setHorizontalGroup(
            cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadJoqueiLayout.createSequentialGroup()
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cadJoqueiLayout.createSequentialGroup()
                            .addGap(298, 298, 298)
                            .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alturaJoq, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(nomeJoq)
                                .addComponent(emailJoq)
                                .addComponent(idadeJoq)
                                .addComponent(pesoJoq)))
                        .addGroup(cadJoqueiLayout.createSequentialGroup()
                            .addGap(362, 362, 362)
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel31)))
                    .addGroup(cadJoqueiLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addGroup(cadJoqueiLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(13, 13, 13)
                                    .addComponent(telJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadJoqueiLayout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(entrarInfoJoquei, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(207, 207, 207))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadJoqueiLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cpfJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        cadJoqueiLayout.setVerticalGroup(
            cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadJoqueiLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(35, 35, 35)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idadeJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pesoJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(alturaJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(telJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(cadJoqueiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJoq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(35, 35, 35)
                .addComponent(entrarInfoJoquei, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        cards.add(cadJoquei, "cadJoquei");

        cadCavalo.setBackground(new java.awt.Color(50, 50, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Peso");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Idade");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Raça");

        idadeCav.setBackground(new java.awt.Color(128, 128, 128));
        idadeCav.setForeground(new java.awt.Color(255, 255, 255));

        pesoCav.setBackground(new java.awt.Color(128, 128, 128));
        pesoCav.setForeground(new java.awt.Color(255, 255, 255));
        pesoCav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoCavActionPerformed(evt);
            }
        });

        nomeCav.setBackground(new java.awt.Color(128, 128, 128));
        nomeCav.setForeground(new java.awt.Color(255, 255, 255));

        entrarInfoCavalo.setBackground(new java.awt.Color(0, 74, 173));
        entrarInfoCavalo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entrarInfoCavalo.setForeground(new java.awt.Color(255, 255, 255));
        entrarInfoCavalo.setText("Cadastrar");
        entrarInfoCavalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarInfoCavaloActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Olá!");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Bem Vindo");

        racaCav.setBackground(new java.awt.Color(128, 128, 128));
        racaCav.setForeground(new java.awt.Color(255, 255, 255));
        racaCav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a raça ...", "Puro-Sangue Inglês", "Quarto de milha", "Árabe", "Standardbred" }));

        javax.swing.GroupLayout cadCavaloLayout = new javax.swing.GroupLayout(cadCavalo);
        cadCavalo.setLayout(cadCavaloLayout);
        cadCavaloLayout.setHorizontalGroup(
            cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadCavaloLayout.createSequentialGroup()
                .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadCavaloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18))
                    .addGroup(cadCavaloLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(23, 23, 23)))
                .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idadeCav)
                    .addComponent(pesoCav, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(nomeCav)
                    .addComponent(racaCav, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadCavaloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(entrarInfoCavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
            .addGroup(cadCavaloLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cadCavaloLayout.setVerticalGroup(
            cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadCavaloLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadCavaloLayout.createSequentialGroup()
                        .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(racaCav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(idadeCav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(cadCavaloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pesoCav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(entrarInfoCavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        cards.add(cadCavalo, "cadCavalo");

        corrida.setBackground(new java.awt.Color(50, 50, 50));
        corrida.setForeground(new java.awt.Color(255, 255, 255));

        selectCorrida.setBackground(new java.awt.Color(128, 128, 128));
        selectCorrida.setForeground(new java.awt.Color(255, 255, 255));
        selectCorrida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Corrida ..." }));

        selectCav.setBackground(new java.awt.Color(128, 128, 128));
        selectCav.setForeground(new java.awt.Color(255, 255, 255));
        selectCav.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o cavalo ..." }));

        selectJoq.setBackground(new java.awt.Color(128, 128, 128));
        selectJoq.setForeground(new java.awt.Color(255, 255, 255));
        selectJoq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Joquei ..." }));
        selectJoq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectJoqActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Corridas");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nome do Cavalo");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Nome do Joquei");

        btnEntrarCorrida.setBackground(new java.awt.Color(0, 74, 173));
        btnEntrarCorrida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEntrarCorrida.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarCorrida.setText("Entrar");
        btnEntrarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCorridaActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Bem Vindo");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Olá!");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total a Gastar: ");

        lblgasto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblgasto.setForeground(new java.awt.Color(255, 255, 255));
        lblgasto.setText("R$");

        javax.swing.GroupLayout corridaLayout = new javax.swing.GroupLayout(corrida);
        corrida.setLayout(corridaLayout);
        corridaLayout.setHorizontalGroup(
            corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corridaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
            .addGroup(corridaLayout.createSequentialGroup()
                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corridaLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(corridaLayout.createSequentialGroup()
                                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectCav, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectJoq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(corridaLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel27)
                                .addGap(47, 47, 47)
                                .addComponent(selectCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(corridaLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34))
                    .addGroup(corridaLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        corridaLayout.setVerticalGroup(
            corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corridaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(selectCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(selectCav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(selectJoq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(corridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(176, 176, 176)
                .addComponent(btnEntrarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cards.add(corrida, "corrida");

        perfil.setBackground(new java.awt.Color(50, 50, 50));
        perfil.setForeground(new java.awt.Color(255, 255, 255));
        perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Trocar Senha");
        perfil.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 393, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Telefone");
        perfil.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 254, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nome");
        perfil.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 165, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Senha");
        perfil.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 343, -1, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Email");
        perfil.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 204, -1, -1));

        mudarSenhaBut.setBackground(new java.awt.Color(0, 74, 173));
        mudarSenhaBut.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mudarSenhaBut.setForeground(new java.awt.Color(255, 255, 255));
        mudarSenhaBut.setText("Trocar Senha");
        mudarSenhaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudarSenhaButActionPerformed(evt);
            }
        });
        perfil.add(mudarSenhaBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 491, 202, 75));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Olá!");
        perfil.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 41, -1, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Bem Vindo");
        perfil.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 41, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CPF");
        perfil.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 304, -1, -1));

        telUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        telUser.setForeground(new java.awt.Color(255, 255, 255));
        perfil.add(telUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 254, 500, 32));

        nomeUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeUser.setForeground(new java.awt.Color(255, 255, 255));
        perfil.add(nomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 165, 500, 32));

        cpfUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cpfUser.setForeground(new java.awt.Color(255, 255, 255));
        perfil.add(cpfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 304, 500, 32));

        emailUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailUser.setForeground(new java.awt.Color(255, 255, 255));
        perfil.add(emailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 204, 500, 32));

        senhaUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        senhaUser.setForeground(new java.awt.Color(255, 255, 255));
        senhaUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        perfil.add(senhaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 343, 500, 32));

        MudSenha.setBackground(new java.awt.Color(128, 128, 128));
        MudSenha.setForeground(new java.awt.Color(255, 255, 255));
        perfil.add(MudSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 397, 500, -1));

        back.setText("Sair");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        perfil.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 645, -1, -1));

        mostrarSenha.setForeground(new java.awt.Color(255, 255, 255));
        mostrarSenha.setText("Mostrar senha");
        mostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSenhaActionPerformed(evt);
            }
        });
        perfil.add(mostrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, -1, -1));

        cards.add(perfil, "perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perfClick)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(perfClick)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cavCadButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cavCadButActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"cavalosCad");
        listaCav.setModel(info.pegarCavalos(pegarCpf()));
    }//GEN-LAST:event_cavCadButActionPerformed
    
    public ArrayList mostrarDadosDono(){
        ArrayList dados = new ArrayList();
        try{
            String sql = "SELECT * FROM usuario WHERE cpf = ?;";
            PreparedStatement pstm = con.prepareStatement(sql);
            pstm.setLong(1, pegarCpf());
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
                dados.add(rs.getLong("cpf"));
                dados.add(rs.getString("nome"));
                dados.add(rs.getString("senha"));
                dados.add(rs.getString("email"));
                dados.add(rs.getString("telefone"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
        return dados;
    }
    
    private void entCorriButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entCorriButActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"corrida"); 
        selectJoq();
        selectCav();
        selectCor();
    }//GEN-LAST:event_entCorriButActionPerformed

    private void homeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"home");
        
        topCav.setModel(info.top3Cavalos(pegarCpf()));
    }//GEN-LAST:event_homeButActionPerformed

    private void cadJoqButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadJoqButActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"cadJoquei");
    }//GEN-LAST:event_cadJoqButActionPerformed

    private void cadCavButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCavButActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"cadCavalo");
    }//GEN-LAST:event_cadCavButActionPerformed

    private void perfClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfClickMouseClicked
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"perfil");
    }//GEN-LAST:event_perfClickMouseClicked

    private void entrarInfoJoqueiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarInfoJoqueiActionPerformed
        // TODO add your handling code here:
        Dono dono = new Dono();
        
        String nome = nomeJoq.getText();
        String email = emailJoq.getText();
        int idade = Integer.parseInt(idadeJoq.getText());
        float peso = Float.parseFloat(pesoJoq.getText());
        float altura = Float.parseFloat(alturaJoq.getText());
        String fone = telJoq.getText();
        long cpf = Long.parseLong(cpfJoq.getText());
        dono.cadastroJoquei(con, cpf, nome, idade, fone, email, peso, altura, pegarCpf());
        
        if (dono.getFlagj() == 1){
            nomeJoq.setText("");
            idadeJoq.setText("");
            pesoJoq.setText("");
            alturaJoq.setText("");
            emailJoq.setText("");
            telJoq.setText("");
            cpfJoq.setText("");
        }
    }//GEN-LAST:event_entrarInfoJoqueiActionPerformed

    public void selectCav(){

        DefaultListModel dlm = info.pegarCavalos(pegarCpf());
        
        selectCav.removeAllItems();
        selectCav.addItem("Selecione o cavalo...");
        
        for (int i = 0; i < dlm.size(); i++){
            selectCav.addItem(String.valueOf(dlm.getElementAt(i)));
        }
    }
    
    public void selectJoq(){
        
        DefaultListModel dlm = info.buscarJoqueis(pegarCpf());
        
        selectJoq.removeAllItems();
        selectJoq.addItem("Selecione o jóquei...");
        
        for (int i = 0; i < dlm.size(); i++){
            selectJoq.addItem(String.valueOf(dlm.getElementAt(i)));
        }
    }
    
    public void selectCor(){
        
        DefaultListModel dlm = info.buscarCorridas("Aberta");
        
        selectCorrida.removeAllItems();
        selectCorrida.addItem("Selecione a corrida...");
        
        for (int i = 0; i < dlm.size(); i++){
            selectCorrida.addItem(String.valueOf(dlm.getElementAt(i)));
        }
    }
    
    private void telJoqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telJoqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telJoqActionPerformed

    private void pesoCavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoCavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoCavActionPerformed

    private void entrarInfoCavaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarInfoCavaloActionPerformed
        // TODO add your handling code here:
        Dono dono = new Dono();
        
        long cpf = this.pegarCpf();
        
        String nome = nomeCav.getText();
        int raca = racaCav.getSelectedIndex();
        int idade = Integer.parseInt(idadeCav.getText());
        float peso = Float.parseFloat(pesoCav.getText());
        
        dono.cadastroCavalo(con, nome, idade, peso, cpf, raca);
        
        if (dono.getFlagc() == 1){
            nomeCav.setText("");
            racaCav.setSelectedIndex(0);
            idadeCav.setText("");
            pesoCav.setText("");
        }
    }//GEN-LAST:event_entrarInfoCavaloActionPerformed

    public long pegarCpf(){
        ConexaoBD cbd = new ConexaoBD();
        Connection con = cbd.connectionMySql();
        
        long cpf = 0;
        try{
            String query = "SELECT cpf FROM usuario WHERE email = ?;";
            PreparedStatement stat = con.prepareStatement(query);
            stat.setString(1, email);
            ResultSet result  = stat.executeQuery();
            while (result.next()){
                cpf = result.getLong("cpf");
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro!!\n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
        }
        return cpf;
    }
    
    public String nomeDn(){
        
        String nome = "";
        try{
            String sql = "SELECT nome FROM usuario WHERE cpf = " +pegarCpf();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()){
                nome = rs.getString("nome");
            }
        } catch (SQLException e){
            System.out.println(e);
        }
        return nome;
    }
    
    private void selectJoqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectJoqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectJoqActionPerformed

    public String[] repararString(String repara){
        String tipo;
        String[] cavname = new String[2];
        cavname = repara.split(" -->");
        String horse = cavname[0];
        String resto = cavname[1];
        String[] race = resto.split(", ");
        if(race.length == 3){
            tipo = race[1];
        }else{
            tipo = race[3];
        }
        String[] retorno = new String[2];
        retorno[0] = horse;
        retorno[1] = tipo;
        return retorno;
    }
    
    private void btnEntrarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCorridaActionPerformed
        String corrida = selectCorrida.getSelectedItem().toString();
        String cavalo = selectCav.getSelectedItem().toString();
        selectJoq.getSelectedItem().toString();
        String horse = repararString(cavalo)[0];
        String race = repararString(corrida)[0];
        String raceType = repararString(corrida)[1];
        
        long cpf = pegarCpf();
        Dono dn = new Dono();
        int idcav = dn.idCavalo(con, cpf, horse);
        int idcor = dn.idCorrida(con, race);
        
        float gastos = dn.showGastos(raceType);
        
        int op = JOptionPane.showConfirmDialog(null, "Você irá gastar " + df.format(gastos), "Entrar na corrida", JOptionPane.OK_CANCEL_OPTION);
        if (op == 0){
            AddCred cr = new AddCred();
            if (cr.pegarSaldo(con, email) >= gastos){
                cr.Remover(con, email, gastos);
                dn.entrarCorrida(con, idcav, idcor);
                jLabel22.setText(String.valueOf(df.format(cr.pegarSaldo(con, email))));
            } else {
                JOptionPane.showMessageDialog(null, "Saldo insuficiente! Adicione saldo na página inicial", "Sem créditos", JOptionPane.ERROR_MESSAGE);
            }
        }
        selectCor();
        selectCav();
        selectJoq();
        lblgasto.setText(df.format(gastos));
    }//GEN-LAST:event_btnEntrarCorridaActionPerformed

    private void mudarSenhaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudarSenhaButActionPerformed
        Dono dn = new Dono();
        String oldSenha = senhaUser.getText();
        String novaSenha = MudSenha.getText();
        
        String senha = JOptionPane.showInputDialog("Qual a sua senha atual?");
        if (senha.equals(oldSenha)){
            int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo mudar a sua senha?", "Mudar senha", JOptionPane.YES_NO_OPTION);
            if (op == 0){
                dn.trocarSenha(con, pegarCpf(), oldSenha, novaSenha);
                newSenha = dn.mostrarSenha(con, pegarCpf(), emailUser.getText());
                senhaUser.setText(newSenha);
                MudSenha.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha errada!!", "Mudar senha", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_mudarSenhaButActionPerformed

    private void adiciSaldobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiciSaldobutActionPerformed
        // TODO add your handling code here:
        AddCred adcr = new AddCred();
        
        float valor = Float.parseFloat(adiciSaldo.getText());
        int op = JOptionPane.showConfirmDialog(null, "Deseja adicionar " +df.format(valor) +" de créditos?", "Adição de créditos", JOptionPane.OK_CANCEL_OPTION);
        if (op == 0){
            adcr.Adicionar(con, email, valor);
            saldo = adcr.pegarSaldo(con, email);
            jLabel22.setText(String.valueOf(df.format(saldo)));
            JOptionPane.showMessageDialog(null, "Foram adicionados " +df.format(valor) +" de créditos na sua conta.\nSeu saldo agora é de " +df.format(saldo), "´Créditos adicionados", JOptionPane.INFORMATION_MESSAGE);
            adiciSaldo.setText("");
        }
    }//GEN-LAST:event_adiciSaldobutActionPerformed
    
    private void jLabel22InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLabel22InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22InputMethodTextChanged

    private void entPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entPerfilActionPerformed
        CardLayout c1 = (CardLayout) cards.getLayout();
        c1.show(cards,"perfil");
        ArrayList dados = new ArrayList();
        for(Object d : mostrarDadosDono()){
            dados.add(d);
        }
        cpfUser.setText(dados.get(0).toString());
        nomeUser.setText(dados.get(1).toString());
        senhaUser.setText(dados.get(2).toString());
        emailUser.setText(dados.get(3).toString());
        telUser.setText(dados.get(4).toString());
    }//GEN-LAST:event_entPerfilActionPerformed

    private void homeButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseEntered
        homeBut.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_homeButMouseEntered

    private void homeButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButMouseExited
        homeBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_homeButMouseExited

    private void cavCadButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cavCadButMouseEntered
        cavCadBut.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_cavCadButMouseEntered

    private void cavCadButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cavCadButMouseExited
        cavCadBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_cavCadButMouseExited

    private void cadJoqButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadJoqButMouseEntered
        cadJoqBut.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_cadJoqButMouseEntered

    private void cadJoqButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadJoqButMouseExited
        cadJoqBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_cadJoqButMouseExited

    private void cadCavButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCavButMouseEntered
        cadCavBut.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_cadCavButMouseEntered

    private void cadCavButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCavButMouseExited
        cadCavBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_cadCavButMouseExited

    private void entCorriButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entCorriButMouseEntered
        entCorriBut.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_entCorriButMouseEntered

    private void entCorriButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entCorriButMouseExited
        entCorriBut.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_entCorriButMouseExited

    private void entPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entPerfilMouseEntered
        entPerfil.setBackground(new Color(0, 74, 173));// TODO add your handling code here:
    }//GEN-LAST:event_entPerfilMouseEntered

    private void entPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entPerfilMouseExited
        entPerfil.setBackground(new Color(66,66,66));// TODO add your handling code here:
    }//GEN-LAST:event_entPerfilMouseExited

    private void mostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaActionPerformed
        // TODO add your handling code here:
        if(mostrarSenha.isSelected()){
            MudSenha.setEchoChar('\u0000');
        }  
        else {
            MudSenha.setEchoChar('*'); 
        }
    }//GEN-LAST:event_mostrarSenhaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Sair", JOptionPane.YES_NO_OPTION);
        
        if(op == 0){
            Login log = new Login();
            log.setVisible(true);
            log.setLocationRelativeTo(null);
            dispose();
        }
    }//GEN-LAST:event_backActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuDono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuDono().setVisible(true);
            }
        });
    }

    Connection con;
    String email;
    float saldo;
    String newSenha;
    DecimalFormat df = new DecimalFormat("R$ #,##0.00");

    BuscarInfo info = new BuscarInfo();
    
    public void recebe(Connection conec, String em, float sal){
        con = conec;
        email = em;
        saldo = sal;
        
        String[] nome= nomeDn().split(" ");
        
        jLabel2.setText("Bem-vindo, " + nome[0]);
        jLabel17.setText("Bem-vindo, " + nome[0]);
        jLabel31.setText("Bem-vindo, " + nome[0]);
        jLabel33.setText("Bem-vindo, " + nome[0]);
        jLabel34.setText("Bem-vindo, " + nome[0]);
        jLabel42.setText("Bem-vindo, " + nome[0]);
        jLabel22.setText(String.valueOf(df.format(saldo)));
        topCav.setModel(info.top3Cavalos(pegarCpf()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField MudSenha;
    private javax.swing.JTextField adiciSaldo;
    private javax.swing.JButton adiciSaldobut;
    private javax.swing.JTextField alturaJoq;
    private javax.swing.JButton back;
    private javax.swing.JButton btnEntrarCorrida;
    private javax.swing.JButton cadCavBut;
    private javax.swing.JPanel cadCavalo;
    private javax.swing.JButton cadJoqBut;
    private javax.swing.JPanel cadJoquei;
    private javax.swing.JPanel cards;
    private javax.swing.JButton cavCadBut;
    private javax.swing.JPanel cavalosCad;
    private javax.swing.JPanel corrida;
    private javax.swing.JTextField cpfJoq;
    private javax.swing.JLabel cpfUser;
    private javax.swing.JTextField emailJoq;
    private javax.swing.JLabel emailUser;
    private javax.swing.JButton entCorriBut;
    private javax.swing.JButton entPerfil;
    private javax.swing.JButton entrarInfoCavalo;
    private javax.swing.JButton entrarInfoJoquei;
    private javax.swing.JPanel home;
    private javax.swing.JButton homeBut;
    private javax.swing.JTextField idadeCav;
    private javax.swing.JTextField idadeJoq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblgasto;
    private javax.swing.JList<String> listaCav;
    private javax.swing.JCheckBox mostrarSenha;
    private javax.swing.JButton mudarSenhaBut;
    private javax.swing.JTextField nomeCav;
    private javax.swing.JTextField nomeJoq;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JLabel perfClick;
    private javax.swing.JPanel perfil;
    private javax.swing.JTextField pesoCav;
    private javax.swing.JTextField pesoJoq;
    private javax.swing.JComboBox<String> racaCav;
    private javax.swing.JComboBox<String> selectCav;
    private javax.swing.JComboBox<String> selectCorrida;
    private javax.swing.JComboBox<String> selectJoq;
    private javax.swing.JLabel senhaUser;
    private javax.swing.JTextField telJoq;
    private javax.swing.JLabel telUser;
    private javax.swing.JList<String> topCav;
    // End of variables declaration//GEN-END:variables
}
